### ISSUE TITLE
Dracula gedit theme cannot be applied / is not listed as a theme

### ISSUE THREAD

**Issue by eerdjan-tech** [dracula/gedit#13] opened 2024-04-25 13:45 UTC
The Dracula gedit theme can be downloaded and the xml file can be saved following the described directions. However the Dracula theme will not be listed in the preferences.

This appears to be due to the fact that the stated version is not been included in the current xml file.

Current xml = <style-scheme id="dracula" name="Dracula" kind="dark">
<_description>A dark theme for Gedit</_description>

Previous xml = <style-scheme id="dracula" name="Dracula" version="1.0">
<author>Ricardo Madriz</author>
<_description>A dark theme for Gedit</_description>

When manually including the line - version="1.0" - the file is listed in the gedit preferences and can be applied successfully.

**Comment by richin13** [comment] 2024-04-25 13:54
Hey, thanks for the reporting. This is a duplicate of https://github.com/dracula/gedit/issues/12 so let's track it there 👍🏼

**Closed as completed by richin13** 2024-04-25 13:54 UTC

**Comment by eerdjan-tech** [comment] 2024-04-25 14:15
👍🏼
